import Head from "next/head";
import Image from "next/image";
import Spline from "@splinetool/react-spline";

export default function Home() {
  return (
    <>
      <Head>
        <title>Teun Spithoven</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta content="Teun Spithoven" property="og:title" />
        <meta
          content="Portfolio van mijn ICT avonturen tot nu toe"
          property="og:description"
        />
        <meta content="https://teun.firebaseapp.com/" property="og:url" />
        <meta
          content="https://teun.firebaseapp.com/assets/teun portret.jpg"
          property="og:image"
        />
        <meta content="#43B581" data-react-helmet="true" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="absolute w-full h-96">
        <Spline scene="https://prod.spline.design/wFgGuz25sEF624km/scene.splinecode" />
      </div>
      <div className="absolute mt-96">
        <div
          className="columns-1 lg:columns-2 py-4 px-4 sm:px-10 lg:px-16 xl:px-32 bg-gradient-to-br from-blue-200 via-blue-300 to-blue-400"
          id="about"
        >
          <div id="about me">
            <h2 className="font-semibold font-sans text-xl">About me</h2>
            <p>
              In 2020, I started my IT journey at Fontys. They showed me some
              different workfields in IT during the first semester and in the
              end my preference was software engineering, and that's what I have
              been doing from that moment forward. The goal of creating this
              portfolio is to create a summary of my Software Engineering
              journey.
            </p>
          </div>
          <div id="skills mt-10 lg:pt-0">
            <h3 className="font-semibold font-sans text-xl">My Skills</h3>
            <p className="">Web Application Development</p>
            <p className="">Vue Js</p>
            <p className="">C#</p>
            <p className="">Python</p>
          </div>
        </div>

        <div
          className="px-4 sm:px-10 lg:px-16 xl:px-32 py-4 bg-slate-300"
          id="photos"
        >
          <h2 className="font-semibold font-sans text-4xl pb-4">My Projects</h2>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-10">
            <div className="h-auto">
              <h3 className="font-semibold font-sans text-xl">
                Euro to Dollar converter
              </h3>
              <p>
                In my first semester I learned my first programming language:
                C#. During this semester I learned about programming by making
                practical assignments, by making an application that converts
                euros to dollars for example.
              </p>
              <Image
                src="/assets/S1/eurodollarconverter.png"
                alt="euro to dollar converter screenshot"
                width={1000}
                height={1000}
              />
              {/* <img
                src="./assets/S1/eurodollarconverter.png"
                alt="euro to dollar converter screenshot"
              ></img> */}
            </div>
            <div className="1">
              <h3 className="font-semibold font-sans text-xl">
                Shop register system
              </h3>
              <p>
                After making more of these little assignments I made my final
                project of my first semester. It is a shopping system that has a
                shopping cart and check out simulation.
              </p>
              <img
                src="./assets/S1/winkel2.png"
                alt="windows forms shopping app"
              ></img>
              <img
                src="./assets/S1/betalen.png"
                alt="paying screen in windows forms shopping app"
              ></img>
            </div>
            <div className="2">
              <h3 className="font-semibold font-sans text-xl">StudyCluster</h3>
              <p>
                In the second half of the first semester I participated in a
                group project where I made a electronic learning environment for
                schools with 5 other classmates. In this assignment we made a
                class diagram for our .NET OOP application. This assignment also
                was the first time that I worked with a database.
              </p>
              <img src="./assets/S1/classdiagram.png" alt="class diagram"></img>
              <img
                src="./assets/S1/eloscheduleitemform.png"
                alt="ELO schedule"
              ></img>
              <img src="./assets/S1/elohomepage.png" alt="ELO homepage"></img>
            </div>
            <div className="2">
              <h3 className="font-semibold font-sans text-xl">Circustrain</h3>
              <p>
                In semester 2 of the study, i wrote a program that sorts circus
                animals into train wagons in the most efficient way, without
                braking any of the given rules. My application designing skills
                improved a lot because of this exercise.
              </p>
              <img
                src="./assets/S2/circustreinflowchart.png"
                alt="flowchart"
              ></img>
            </div>
            <div className="3">
              <h3 className="font-semibold font-sans text-xl">Dream Journal</h3>
              <p>
                In semester 2 I had my first encounter with UI design and
                multi-layered applications. I made an app that can be used to
                keep track of your dreams and see your friends dreams.
              </p>
              <img
                src="./assets/S2/dreamyournaluidesign.png"
                alt="dream yournal app design"
              ></img>
            </div>
            <div className="3">
              <h3 className="font-semibold font-sans text-xl">
                Bolus calculator
              </h3>
              <p>
                In semester 2 I also did a group project for the company
                Philips, we made a distributed application with a typescript
                frontend and typescript backend, those layers communicate
                through express. During this project I also learned how to write
                unit tests.
              </p>
              <img src="./assets/S2/jest.png" alt="jest tests"></img>
            </div>
            <div className="4">
              <h3 className="font-semibold font-sans text-xl">Ninja Game</h3>
              <p>
                In my third semester I made a web application with Python,
                Django, Node and VueJs. For this distributed web app I made one
                frontend application with Vuejs and two different Django
                backends. One for handling user authentication and the saving of
                used data, and the other one as my game server. This game server
                uses a websocket for fast back and forth communication between
                client and server. My software testing skills improved a lot
                during this project, I wrote unit, integration and end to end
                tests. I used Cypress to test my frontend. All of these tests
                where automatically run after pushing changes to my Github
                repository because of the CI/CD pipeline.
              </p>
              <img src="./assets/S3/CICD.png" alt="github actions CI/CD"></img>
            </div>
          </div>
        </div>
        <div
          className="px-4 sm:px-10 lg:px-16 xl:px-32 py-4 bg-gradient-to-tr from-gray-300 via-gray-400 to-gray-500"
          id="contact"
        >
          <h2 className="font-semibold font-sans text-xl">Contact Me</h2>

          <div className="w3-section">
            <p>
              <i className="fa fa-map-marker fa-fw w3-text-white w3-xxlarge w3-margin-right"></i>{" "}
              Eersel, NL
            </p>
            <p>
              <i className="fa fa-phone fa-fw w3-text-white w3-xxlarge w3-margin-right"></i>{" "}
              Phone: +31 6 19518380
            </p>
            <p>
              <i className="fa fa-envelope fa-fw w3-text-white w3-xxlarge w3-margin-right">
                {" "}
              </i>{" "}
              Email: teun.spithoven@gmail.com
            </p>
          </div>

          <footer className="w3-content w3-padding-64 w3-text-grey w3-xlarge">
            <a
              href="https://github.com/TeunSpithoven"
              title="github"
              target="_blank"
              rel="noopener noreferrer"
            >
              <i className="fa fa-github w3-hover-opacity"></i>
            </a>
            <a
              href="https://www.instagram.com/teun.spithoven/"
              title="instagram"
              target="_blank"
              rel="noopener noreferrer"
            >
              <i className="fa fa-instagram w3-hover-opacity"></i>
            </a>
            <a
              href="https://www.linkedin.com/in/teun-spithoven/"
              title="linkedIn"
              target="_blank"
              rel="noopener noreferrer"
            >
              <i className="fa fa-linkedin w3-hover-opacity"></i>
            </a>
          </footer>
        </div>
      </div>
    </>
  );
}
